### ISSUE TITLE
TypeError: _obtain_input_shape() got an unexpected keyword argument 'dim_ordering'

### ISSUE THREAD

**Issue by MartinThoma** [titu1994/DenseNet#10]
```
Traceback (most recent call last):
  File "cifar10.py", line 31, in <module>
    growth_rate=growth_rate, nb_filter=nb_filter, dropout_rate=dropout_rate)
  File "DenseNet/densenet.py", line 98, in DenseNet
    include_top=include_top)
TypeError: _obtain_input_shape() got an unexpected keyword argument 'dim_ordering'
```

**Comment by MartinThoma** [comment]
I think it is now called `data_format`: https://github.com/fchollet/keras/blob/master/keras/applications/imagenet_utils.py#L77

**Comment by titu1994** [comment]
You are right.  However I am currently holding off pushing the update to Keras 2 api since there are a few bugs that need to be addressed. 

Once the Keras 2 api stabilizes (perhaps with the release of Tensorflow 1.1 or 1.2, since by then Keras will be merged into Tensorflow so most of the bugs should be squashed), I will port the code.

In the meantime, you can use my code from the contrib branch https://github.com/titu1994/keras-contrib/blob/master/keras_contrib/applications/densenet.py  to use densenet with Keras 2 api.

**Comment by beyhangl** [comment]
why they are changing parameter name for all new version ?  It's waste of time to find new parameter names for all new version. Same situation for opencv library. What's your problem with parameter names ?

**Comment by titu1994** [comment]
@beyhangl this issue has been fixed since 6+ months ?

**Comment by beyhangl** [comment]
with latest version (2.0.8) it's not working again.

**Comment by beyhangl** [comment]
i made downgrade to 2.0.0 and works fine.
