### ISSUE TITLE
preprocess scale 0.017

### ISSUE THREAD

**Issue by ahundt** [titu1994/DenseNet#26]
Looking at the [preprocess function](https://github.com/titu1994/DenseNet/blob/master/densenet.py#L72) I see:
```python
 x *= 0.017 # scale values
```
I thought it might be 1/128 but that is 0.0078125. I can't find anywhere else that something similar is done either in upstream implementations or in the keras preprocessing. Do you have information or reasoning regarding this scaling factor?

**Comment by titu1994** [comment]
Primarily, incorrect classification if scaling is not performed. I referred to the Keras-Densenet repo for this right ? Or did I forget that when I rewrote the call

**Comment by titu1994** [comment]
It's approximately 1/58.8 for some reason. I never could find out why this is the case.

**Comment by titu1994** [comment]
Maybe try with 1/255 and see if it still classifies correctly?

**Comment by vfdev-5** [comment]
Actually, the reason of `0.017` is the following:
Originally, they preprocess normalized between `[0.0; 1.0]` RGB images by subtracting a mean value `[0.485, 0.456, 0.406]` and dividing each channel by a corresponding std value from `[0.229, 0.224, 0.225]`, see [here](https://github.com/liuzhuang13/DenseNet/blob/master/datasets/imagenet.lua#L69). 
But as @titu1994 says that the weights are ported from [here](https://github.com/flyyufelix/DenseNet-Keras) and Felix says that the weights were ported from [here](https://github.com/shicai/DenseNet-Caffe), where the preprocessing is 

- BGR mean values [103.94,116.78,123.68] are subtracted
- scale: 0.017 is used, instead of the original std values for image preprocessing

and if you compute the inverse of `255 * mean(std)`, it gives `1.0 / (255.0 * 0.227) = 0.01727563272004837`

HTH

**Comment by titu1994** [comment]
Thank you very much for the explanation @vfdev-5 !

**Comment by ahundt** [comment]
@vfdev-5 good sleuthing, thanks!
