### ISSUE TITLE
Submit Pull request to keras-contrib?

### ISSUE THREAD

**Issue by ahundt** [titu1994/DenseNet#4]
Keras has created a new official keras-contrib repository where they will accept a broader range of contributions than mainline keras, for eventual inclusion in mainline if it becomes widely used. Would you consider submitting your implementation?

https://github.com/farizrahman4u/keras-contrib

**Comment by titu1994** [comment]
I was reading about that in another issue in Keras.

My question is - Is the script valid to enter the contrib repo ? The only thing it does is create a model. 

The valuable contribution would be the weights of trained models, so I will probably end up adding a PR anyway. 

This is also true for the various other model building scripts I have, many of which aren't in great use. Some examples would be Residual of Residual networks, Wide ResNets and the Densenet for Semantic Segmentation. 

Although I believe that adding the Snapshot Ensemble repo will be a worthwhile addition since it is a simple callback.

**Comment by ahundt** [comment]
yeah I agree, just thought it would be good to let you know about it because your implementations are pretty nice and clean. :-)

I might be tweaking a couple soonish as well.

**Comment by titu1994** [comment]
On further deliberation, I guess I will add the repos even if there are no weights. Certain models are useful to train from scratch, like Warns and DenseNets. 

Thanks for the heads up
